######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 24 12:31:14 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += memory.h
SOURCES += main.cpp memory.cpp
