######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 25 12:42:09 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += memory.h
SOURCES += main.cpp memory.cpp
